// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ярослав",
            "url": "https://github.com/goggle-source",
            "email": "asssv0423348@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category/create_category": {
            "post": {
                "description": "Создание новой категории для зарегистрировшегося пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Создание Категории",
                "parameters": [
                    {
                        "description": "данные для создание новой категории",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_categories.RequestCreateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание категории",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректено введены данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/category/delete_category": {
            "delete": {
                "description": "Удаление категории конкретного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Удаление категории",
                "parameters": [
                    {
                        "description": "userID для удаление категории",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_categories.IDCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/category/get_category": {
            "get": {
                "description": "Получение категории для конкретного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Получение категории",
                "parameters": [
                    {
                        "description": "userID для получение категории",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_categories.IDCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/category/update_category": {
            "put": {
                "description": "Обновление всех характеристики категории",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "обновление пользователя",
                "parameters": [
                    {
                        "description": "данные для обновление категории",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_categories.RequestUpdateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registration/get_accsess_token": {
            "post": {
                "description": "Получение токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "Получение токена",
                "parameters": [
                    {
                        "description": "для получение accsess токена",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Получение access токена",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/registration/login": {
            "post": {
                "description": "Вход пользователя в систему",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Данные для авторизации пользователя",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.UserAuthentication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Авторизация пользователя",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registration/register": {
            "post": {
                "description": "Создание нового пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации пользователя",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.UserRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Регистрация пользователя",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/delete": {
            "post": {
                "description": "Удаление пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Удаление пользователя",
                "parameters": [
                    {
                        "description": "данные для удаление пользователя",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.UserDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Удаление пользователя",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_financial_tracer_internal_handlers_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_financial_tracer_internal_handlers_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "github_com_financial_tracer_internal_handlers_api.SuccessResponse": {
            "type": "object",
            "properties": {
                "value": {}
            }
        },
        "internal_handlers_categories.IDCategory": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers_categories.RequestCreateCategory": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_categories.RequestUpdateCategory": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_user.RefreshToken": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_user.UserAuthentication": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_user.UserDelete": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_user.UserRegistration": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/financial_tracker",
	Schemes:          []string{},
	Title:            "Финансовый Трекер",
	Description:      "API для работы с финансовым трекером",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
